Add MLnz20 magnitude computed from Rapid (Beta VSc7-nightly)
GeoNet/data pull request #730
Opened 2024-12-20 01:55 UTC by salichon

- First commit for Temporary MLnz20 Network Magnitude data sets 
- Comes from recomputed network magnitude from GeoNet Rapid 
- Version Sc7-nightly Mlnz20 "beta" ( seiscomp development   version)
- Example fo CSV file display 

Will be further improved

2024-12-20 02:02 UTC, elidana commented
first quick comment: is there a reason why you're using `;` instead of the `,` character?

2024-12-22 20:23 UTC, salichon commented
nope and the ";"  can be changed to ","  :)

2024-12-22 23:22 UTC, salichon commented
Update @elidana and "functional" 
~20000 events all magnitude range Jan to Dec 2024
Range of magnitude could be reworked ( only >3) if needed

2025-01-08 01:12 UTC, salichon commented
MLnz20 data Update to  End of december 2024 
- that should be all for the year
-  23091 Mlnz20 network magnitudes

2025-01-22 23:07 UTC, JonoHanson approved these changes
nice Jerome, thanks.

probably needs a bit more of a technical review @ozym  or @staylorofford, but at the high level I'm happy.

2025-01-23 00:51 UTC, ozym commented
I suggest that leading space be removed from the entries (this is for machines not people).

I suggest that the dates be ISO3339  formatted (basically add a 'Z' after the date).

2025-01-23 23:20 UTC, salichon commented
- Changes performed as @ozym  advised.
- Rephrased the READMEs

Note The dataset could also be simplified with only  the eventID, MLnz20 and  MLv entries.

2025-02-02 21:55 UTC, salichon commented
Kia Ora @jristau ! 
As a potential user , Would you bring some feed back ? 
(as in too much information or not ?) Thanks ! :) 
We could limit the content to  basic network magntitude information. 
cheers

2025-02-03 21:06 UTC, jristau commented
> Kia Ora @jristau ! As a potential user , Would you bring some feed back ? (as in too much information or not ?) Thanks ! :) We could limit the content to basic network magnittude information. cheers

Hi @salichon I can't see the CSV file except for the first 35 lines with the descriptive information, or at least I can't figure out how to see it. However, all that information makes sense to me and I don't think it's too much. But without being able to see the rest of the CSV file I can't give any feedback about that part.

2025-02-03 22:17 UTC, salichon commented
Hello @jristau It s a large file of ~23000 events you may have some limitation on your side
although maybe if you try  `view file`  you shall  hjhave acces to the whole: 
Try  https://github.com/GeoNet/data/blob/553c3f93d1383f1de268541200b7b31ffb201e71/MLnz20/MLnz_RapidEvents_2024.csv 

thanks for any comments in addition :)

2025-02-04 01:01 UTC, jristau commented
@salichon Thanks Jerome - I can see the file now. It looks great! The only change I might suggest is the column header 'Ratio' could be 'MLnz/MLv Ratio' or 'MLnz/MLv'. The other column headers are immediately obvious what they are without looking for further information, but for 'Ratio' you would have to look at the descriptive information at the top to find it, or guess what it is.

2025-02-04 02:11 UTC, salichon commented
Thanks a Lot @jristau 
Updated and added january 2025  ina new file 
Cheers

2025-02-04 02:14 UTC, salichon commented
NB @jristau  :) if you want tos ee the file after the changes

on the File display showing no content;  go on the right side by the  `....` button it  will display option to edit the file, so that you can have a browse.

2025-02-11 00:49 UTC, elidana requested changes
Hello @salichon , this looks great, impressive work, and so happy to see it over the line!!! Big big kudos to you and the team!!!

It looks pretty good to me, I have some minor changes I'm proposing (see individual comments), on the `MLnz20/README file`, mostly for readability.

And another couple of things, that are possibly very pedantic:

- shall we use `MLNZ20` (all capital letters) in the file names, text, etc? I see that is the acronym Rhoades et al are using in their paper, and for "google-findability" would be good to use the same style

- for the folder name, is it possible to have a more descriptive one? (if so, the folder and the main README.md will need to be updated accordingly). 

- the headers of the 2024 and 2025 files are not consistent, can you please update them to be consistent with the table in the README?
```
$ head -1 MLnz_RapidEvents_202*
==> MLnz_RapidEvents_2024.csv <==
#EVENT_ID,OT,Lat,Lon,Dep,NrStaMLv,NrStaMLnz,MLv,MLnz,Ratio MLnz/MLv

==> MLnz_RapidEvents_2025.csv <==
#ID,OT,Lat,Lon,Dep,NetworkMLv,NetworkMLnz,MLv,MLnz,Ratio MLnz/MLv
```

2025-02-11 00:49 UTC, elidana commented on MLnz20/README.md
> +This file is a _evaluation dataset_ of the NZ Local network magnitude MLnz20 dataset derived from offline processed Geonet Rapid event data and computed over a separate instance.
minor changes, mainly for readability
```
This file is an _evaluation dataset_ of the New Zealand Local network magnitude MLnz20 dataset (ADD REFERENCE). It is derived from GeoNet Rapid event data processed offline and computed independently from the GeoNet Earthquake Catalogue.
```

2025-02-11 00:49 UTC, elidana commented on MLnz20/README.md
> +This dataset will be superseded as MLnz20 is implemented into GeoNet Rapid Production chain.
I think I understand this bit, but might be word rephrasing that a bit for the non-experts? 
Also happy to leave as is if I'm missing something. 

The things less clear to me are (potentially not of interest for external users?):
- what you mean here with "SeisComp _development_"? if it is capturing the fact that is computed offline and independently from GeoNet Rapid, maybe you can just mention the implementation reference?
- are you able to add a link to GNS Seiscomp Nightly v7.0?
- suggest to change last sentence to something like `This dataset will be superseded once MLnz20 will be fully implemented into GeoNet Rapid Earthquake Catalogue Production system.`

2025-02-11 00:49 UTC, elidana commented on MLnz20/README.md
> +MLnz20 network magnitudes are processed routinely offline every month from GeoNet rapid event automatic and manual solutions. More frequent updates are provided as required (event response for instan
- change `GeoNet Rapid` to `GeoNet Rapid` for consistency with previous paragraph
- change `(event response for instance)` to `(e.g. in response to large earthquake events)`

2025-02-11 00:49 UTC, elidana commented on MLnz20/README.md
> +Events ID and magnitudes are only displayed when MLnz20 and MLv are both successfully computed from the observations.
do you have MLnz20 where event ID are not shown/associated? (sorry for lazy question, i could check myself the csv). If not the sentence might be rewritten for clarity?

2025-02-11 00:49 UTC, elidana commented on MLnz20/README.md
> +Dataset files cover a year maximum provided large number of potential entries.
small rephrasing
```
The MLnz20 dataset is computed from January 2024 onward. 
The dataset will be updated regularly and will be split in yearly files.
```

2025-02-11 00:49 UTC, elidana commented on MLnz20/README.md
> +OT | Event origin time format:yyyy-mm-ddThh:mm:ss.s |
change format to `format:yyyy-mm-ddThh:mm:ss.sZ`

2025-02-13 22:51 UTC, salichon commented on MLnz20/README.md
> +MLnz20 network magnitudes are processed routinely offline every month from GeoNet rapid event automatic and manual solutions. More frequent updates are provided as required (event response for instan
kk

2025-02-14 02:43 UTC, ozym commented
Still suggest you use standard date formats, i.e. ISO3339 see above

e.g. https://github.com/GeoNet/data/blob/c56b0782485774b5acfa452f3175282b6985513d/MLNZ20/MLNZ20_RapidEvents_2024.csv#L23091C1-L23091C51

2025-02-14 02:50 UTC, elidana commented
oh yes, great catch Mark! I agree it shall be fixed.
In my review I only stopped at the first part of the files, didn't noticed that there are still entries that are not in ISO3339

@salichon , there are still ~1780 lines in the 2024 file and all entries in 2025 one that has timestamp with `_` instead of `T`

2025-02-14 02:51 UTC, elidana requested changes
thanks @salichon ! 
please ensure all csv have ISO formatted timestamp (some entries still are `2025-01-31_20:02:30.7Z` instead of `2025-01-31T20:02:30.7Z`

2025-02-16 21:32 UTC, salichon commented
Corrected @elidana sorry
Process mishap ... 
thanks

2025-02-16 21:44 UTC, elidana requested changes
sorry to be a pain @salichon , I can still see differences in the headers
```
==> MLNZ20_RapidEvents_2024.csv <==
#ID,OT,Lat,Lon,Dep,NrStaMLv,NrStaMLNZ20,MLv,MLNZ20,Ratio MLrNZ20/MLv

==> MLNZ20_RapidEvents_2025.csv <==
#ID,OT,Lat,Lon,Dep,NetworkMLv,NetworkMLNZ20,MLv,MLNZ20,Ratio MLNZ20/MLv
```

2025-02-17 01:42 UTC, salichon commented on MLnz20/README.md
> +This file is a _evaluation dataset_ of the NZ Local network magnitude MLnz20 dataset derived from offline processed Geonet Rapid event data and computed over a separate instance.
this is a deleted file

2025-02-17 02:58 UTC, elidana commented
@salichon can you please rebase this and squash all commits into 1? I can review again after that. 
it all looks good to me now, happy to do a quick "approve" once rebased. thanks!

2025-02-17 21:09 UTC, salichon commented
@elidana  
your wish is my command
squahed and beautified
github new ways learnt (hope for now ;)) 
cheerios

2025-02-17 22:03 UTC, elidana approved these changes
thanks a lot monsieur @salichon for patiently bearing with all my comments! 
merge away and great work!!

2025-02-18 01:41 UTC, merged